language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE color_picker_test;' -U postgres
- knex migrate:latest --env=test
- knex seed:run --env=test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: kWElBKAv18tFOd7mnlWaLitKXo8iuP3mTWj4tPvYZZOrTBmkqbFjaX6A5HBZh+Va9h8yZEPyu+J8HTSZzmlqYKAuCBWtOB+2sFN9w8kci8TqZDnN8q/4tQke59KEwObX/7aFX6qNfuEucrjbVrY14DoUP+qzX32jjlvAaTNZxDIo57oLUxK/6A6wee34g2ccf/Z4+V7xVDoRf2+fU5OI7mzW7N/cDKNBRf2Bu4tne0rAcveoWkkZl7T+cAzpOLwUMIeb5hHA7TAJ+odXMhsmqHUvB5msGTGnEvwj2eAt+F9+WRCYcWT35Fojm1J/GkwncHdwfexw2BWesRHZhKyox6z69QJMvtExd2MCLcsWK/jfipMlDwGban0JmlPLpA8jR/PTHTylpdQR/WyTxmrWDY/dCe8/a+aD2Ip2S6XVXWYIfMvysQHC6Mzg+UOOMr8saCw4KpN+gYrd0QtOubdRx3Cq/SymdeZSPlH5O35oUPmwf4GljRfXyUuMqEU5Y3NzC55l3NfYrnE7d8WrBlbscOcG7F3SEo66WCEgZhDRz537RWQi6wDvG121z7Pix0oqIh/Bf56czQcc///XPdtBRQeiEHeZe+TAMLr1Tk1uzcAVOXQhYJA+FRo/kiNOEp0T0mdBgP39aVf7T0h0M3KYN3TDkR24zs2sCqqXMsRK5Kw=
  app: color-picker-be
  skip_cleanup: true
